"""add admin_audit_log for key issuance and revocation

Revision ID: 0a1c9736ca0a
Revises: acabf75146f4
Create Date: 2026-08-24 12:20:37.078040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1c9736ca0a'
down_revision: Union[str, Sequence[str], None] = 'acabf75146f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=False),
    sa.Column('admin_key_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_key_id'), 'admin_audit_log', ['key_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_request_id'), 'admin_audit_log', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_audit_log_request_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_key_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
